nav_u_robot_generator:
  ros__parameters:
    robot_name: [ROBOT_NAME]
    author_name: [AUTHOR_NAME]
    author_email: [AUTHOR_EMAIL]
    width: [WIDTH]
    length: [LENGTH]
    height: [HEIGHT]
    wheel_radius: [WHEEL_RADIUS]
    sensor_offset: [SENSOR_OFFSET_MULT]
    body_color: [BODY_COLOR]
    wheel_color: [WHEEL_COLOR]
    sensor_range: [SENSOR_RANGE]
    sensor_samples: [SENSOR_SAMPLES]
    sensor_noise: [SENSOR_NOISE]
    sensor_type: [SENSOR_TYPE]
    parent_path: [PARENT_PATH]
    shape: [SHAPE]
    max_vel_x: [MAX_VEL_X]
    max_vel_theta: [MAX_VEL_THETA]
